version: '3'
services:
  todoz_db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: password
  todoz_web_app:
    build: .
    command: bash -c "rm -f /Todoz/tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/Todoz
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true 
    depends_on:
      - todoz_db
